Update patch set 20
Patch Set 20:

FAILED: fault-monitor/phosphor-fru-fault-monitor 
c++  -o fault-monitor/phosphor-fru-fault-monitor 'fault-monitor/c0d3e34@@phosphor-fru-fault-monitor@exe/_home_jenkins-op_workspace_ci-repository_openbmc_phosphor-led-manager_build_fault-monitor_xyz_openbmc_project_Led_Fru_Monitor_error.cpp.o' 'fault-monitor/c0d3e34@@phosphor-fru-fault-monitor@exe/fru-fault-monitor.cpp.o' 'fault-monitor/c0d3e34@@phosphor-fru-fault-monitor@exe/monitor-main.cpp.o' -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group /usr/local/lib/powerpc64le-linux-gnu/libsdbusplus.so /lib/powerpc64le-linux-gnu/libsystemd.so /usr/local/lib/libphosphor_logging.so /usr/local/lib/powerpc64le-linux-gnu/libphosphor_dbus.so -Wl,--end-group -Wl,-rpath,/usr/local/lib/powerpc64le-linux-gnu -Wl,-rpath-link,/usr/local/lib/powerpc64le-linux-gnu
/usr/bin/ld: fault-monitor/c0d3e34@@phosphor-fru-fault-monitor@exe/fru-fault-monitor.cpp.o:(.toc+0x38): undefined reference to `vtable for sdbusplus::xyz::openbmc_project::Led::Mapper::Error::MethodError'
/usr/bin/ld: fault-monitor/c0d3e34@@phosphor-fru-fault-monitor@exe/fru-fault-monitor.cpp.o:(.toc+0x40): undefined reference to `typeinfo for sdbusplus::xyz::openbmc_project::Led::Mapper::Error::MethodError'
/usr/bin/ld: fault-monitor/c0d3e34@@phosphor-fru-fault-monitor@exe/fru-fault-monitor.cpp.o:(.toc+0x48): undefined reference to `vtable for sdbusplus::xyz::openbmc_project::Led::Mapper::Error::ObjectNotFoundError'
/usr/bin/ld: fault-monitor/c0d3e34@@phosphor-fru-fault-monitor@exe/fru-fault-monitor.cpp.o:(.toc+0x50): undefined reference to `typeinfo for sdbusplus::xyz::openbmc_project::Led::Mapper::Error::ObjectNotFoundError'
/usr/bin/ld: fault-monitor/c0d3e34@@phosphor-fru-fault-monitor@exe/fru-fault-monitor.cpp.o:(.data.rel.local.DW.ref._ZTIN9sdbusplus3xyz15openbmc_project3Led6Mapper5Error11MethodErrorE[DW.ref._ZTIN9sdbusplus3xyz15openbmc_project3Led6Mapper5Error11MethodErrorE]+0x0): undefined reference to `typeinfo for sdbusplus::xyz::openbmc_project::Led::Mapper::Error::MethodError'
/usr/bin/ld: fault-monitor/c0d3e34@@phosphor-fru-fault-monitor@exe/fru-fault-monitor.cpp.o:(.data.rel.local.DW.ref._ZTIN9sdbusplus3xyz15openbmc_project3Led6Mapper5Error19ObjectNotFoundErrorE[DW.ref._ZTIN9sdbusplus3xyz15openbmc_project3Led6Mapper5Error19ObjectNotFoundErrorE]+0x0): undefined reference to `typeinfo for sdbusplus::xyz::openbmc_project::Led::Mapper::Error::ObjectNotFoundError'
collect2: error: ld returned 1 exit status

-------

Believe we need to add some library dependencies explicitly in Makefile ?.

Patch-set: 20
Reviewer: Gerrit User 1000014 <1000014@adbd0a64-1f21-4d83-b585-671fe73cb6e4>
Label: Code-Review=0