manager: remove unused bus member
Fix the following clang warning:

```
../manager/manager.hpp:140:23: error: private field 'bus' is not used [-Werror,-Wunused-private-field]
  140 |     sdbusplus::bus_t& bus;
      |                       ^
```

I could have removed the bus entirely from the member, but I don't
really like that the utilities create their own bus connection, so
I'll likely refactor that in the future.  There is no point to remove
the parameter only to add it back in.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I12b6a4ea51ea0a375c0f4652acfc4472ab0a0944